### PR TITLE
Add Debounce decorator

### PR DESCRIPTION
**Pull request by yarkovaleksei**

### CODE REVIEW

**Comment by foxbunny** [comment]
I have a two objections to this PR:

1. It modifies the original code style, which is outside the PR's scope
2. Debounce is not a Vue feature (please correct me if I'm wrong), so it's outside of the scope of this package

**Comment by kaorun343** [comment]
Hi.

There are already `@Debounce` decorator published to NPM.

https://github.com/bvaughn/debounce-decorator

**Comment by kaorun343** [comment]
I'll close this, PR.

Please use the decorator I introduced, instead.

Thanks.

**Comment by viT-1** [comment]
@kaorun343 What do you think about https://github.com/zgrybus/debounce-decorator-ts/ ?
It supports umd & type definition file.

**Pull request closed without merging**
