### PR TITLE
feat: Added @Setup() decorator for usage with the composition API.

### PR DESCRIPTION
**Pull request by michealroberts**
feat: Added @Setup() decorator for usage with the composition API. 

Includes associated test suite for expected output.

Includes upgrades to the underlying "vue" and "vue-template-compiler" package versions => 2.7.5.

### CODE REVIEW

**Comment by astraios** [comment]
👍

**Comment by michealroberts** [comment]
@kaorun343 Any thoughts on this PR?

**Comment by kaorun343** [comment]
I think writing setup function in Component decorator is enough and the new decorator is not needed.

**Comment by eugeniomachadoi** [comment]
> I think writing the setup function in the Component decorator is enough and the new decorator is not needed.

Don't you think having the setup in components declaration in the class leaves unnecessary entropy (especially for huge projects who have to migrate to composition gradually) between code inside/outside setup:

image

I dunno, but I feel the proposed idea is better. also, it's very unusual at least for me to have the `setup` inside the Component decorator, then the class declaration followed by the class code.

**Comment by kaorun343** [comment]
You can use `registerHooks` instead of this `@Setup` decorator.

https://class-component.vuejs.org/guide/additional-hooks.html

Also, allowing setup function as a n instance method may causes invalid `this` access. This is why `@Filter` decorator is not included to this library.

**Pull request closed without merging**
